import type { Metadata } from 'next'
import { Onest } from 'next/font/google'
import '../styles/globals.css'
import React from "react";

import { Sidebar } from "@/components/sidebar/sidebar";

const onest = Onest({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
	children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" className="dark">
      <body className={`flex h-screen ${onest.className}`}>
        <Sidebar/>
        <main className="flex flex-col mx-auto md:pl-80 w-full md:w-[1400px] p-8">
          {children}
          <footer
            className="border border-white mt-auto bg-[#FFAFFF]"
          >
				footer
          </footer>
        </main>
      </body>
    </html>
  )
}
