import type { Metadata } from 'next'
import { Onest } from 'next/font/google'
import '../styles/globals.css'
import React from "react";

import { Sidebar } from "@/components/sidebar/sidebar";

const onest = Onest({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
	children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" className="dark">
      <body className={` ${onest.className}`}>
        <div className="flex h-screen">
          <Sidebar/>
          <div className="flex-1 overflow-auto gap-y-6 flex flex-col py-6 px-10">
            <main>
              {children}
            </main>
            <footer
              className="border border-white mt-auto bg-[#FFAFFF]"
            >
					footer
            </footer>
          </div>
        </div>
      </body>
    </html>
  )
}
